name: 'Change Champion Check'
description: 'Check for changesets in a pull request and comment if missing'
author: 'Change Champion'

inputs:
  token:
    description: 'GitHub token for posting comments'
    required: false
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: Read config
      id: config
      shell: bash
      run: |
        if [ -f .changes/config.json ]; then
          PREFIX=$(jq -r '.releaseBranchPrefix // "release/"' .changes/config.json 2>/dev/null || echo "release/")
        else
          PREFIX="release/"
        fi
        echo "release_branch_prefix=$PREFIX" >> $GITHUB_OUTPUT

    - name: Check if release PR
      id: release-check
      shell: bash
      run: |
        HEAD_REF="${{ github.head_ref }}"
        PREFIX="${{ steps.config.outputs.release_branch_prefix }}"
        if [[ "$HEAD_REF" == ${PREFIX}* ]]; then
          echo "is_release=true" >> $GITHUB_OUTPUT
        else
          echo "is_release=false" >> $GITHUB_OUTPUT
        fi

    - name: Fetch base ref
      if: steps.release-check.outputs.is_release == 'false'
      shell: bash
      run: git fetch origin ${{ github.base_ref }} --depth=1

    - name: Check for changeset files
      if: steps.release-check.outputs.is_release == 'false'
      id: changeset-check
      shell: bash
      run: |
        if ! CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD 2>&1); then
          echo "::warning::Could not compute diff against origin/${{ github.base_ref }}: $CHANGED_FILES"
          echo "has_changeset=unknown" >> $GITHUB_OUTPUT
          exit 0
        fi

        CHANGESET_FILES=$(echo "$CHANGED_FILES" | grep -E '^\.changes/.*\.md$' | grep -v 'README.md' || true)

        if [ -z "$CHANGESET_FILES" ]; then
          echo "has_changeset=false" >> $GITHUB_OUTPUT
        else
          echo "has_changeset=true" >> $GITHUB_OUTPUT
        fi

    - name: Comment on PR
      if: steps.changeset-check.outputs.has_changeset == 'false'
      uses: actions/github-script@v8
      continue-on-error: true
      with:
        github-token: ${{ inputs.token }}
        script: |
          const body = `### 📝 No Changeset Found

          This PR does not include a changeset. If this change should be included in the changelog and trigger a release, please add one:

          \`\`\`bash
          champ add
          \`\`\`

          If this change doesn't need a release (e.g., docs, tests, CI), you can ignore this message.

          <details>
          <summary>What is a changeset?</summary>

          A changeset is a markdown file in the \`.changes/\` directory that describes what changed and how it affects the version number (major, minor, or patch).

          </details>`;

          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });

          const botComment = comments.find(comment =>
            comment.user.type === 'Bot' &&
            comment.body.includes('No Changeset Found')
          );

          if (!botComment) {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            });
          }
