name: 'Change Champion Version'
description: 'Process changesets and create a release pull request'
author: 'Change Champion'

inputs:
  php-version:
    description: 'PHP version to use'
    required: false
    default: '8.2'
  version:
    description: 'Version of change-champion to install'
    required: false
    default: 'latest'
  token:
    description: 'GitHub token for creating PRs'
    required: false
    default: ${{ github.token }}

outputs:
  hasChangesets:
    description: 'Whether there are pending changesets'
    value: ${{ steps.changesets.outputs.hasChangesets }}
  version:
    description: 'The next release version'
    value: ${{ steps.changesets.outputs.version }}
  pullRequestNumber:
    description: 'The pull request number if one was created'
    value: ${{ steps.pr.outputs.pull-request-number }}

runs:
  using: 'composite'
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        tools: composer:v2

    - name: Install change-champion
      shell: bash
      run: |
        composer global require change-champion/champ:${{ inputs.version == 'latest' && '*' || inputs.version }}
        echo "$(composer global config bin-dir --absolute)" >> $GITHUB_PATH

    - name: Read config
      id: config
      shell: bash
      run: |
        if [ -f .changes/config.json ]; then
          PREFIX=$(jq -r '.releaseBranchPrefix // "release/"' .changes/config.json 2>/dev/null || echo "release/")
          VERSION_PREFIX=$(jq -r '.versionPrefix // "v"' .changes/config.json 2>/dev/null || echo "v")
        else
          PREFIX="release/"
          VERSION_PREFIX="v"
        fi
        echo "releaseBranchPrefix=$PREFIX" >> $GITHUB_OUTPUT
        echo "versionPrefix=$VERSION_PREFIX" >> $GITHUB_OUTPUT

    - name: Check for changesets
      id: changesets
      shell: bash
      run: |
        if ! STATUS=$(champ status 2>&1); then
          if echo "$STATUS" | grep -q "No pending changesets"; then
            echo "hasChangesets=false" >> $GITHUB_OUTPUT
            echo "No changesets found"
            exit 0
          fi
          echo "::error::champ status failed: $STATUS"
          exit 1
        fi

        if echo "$STATUS" | grep -q "No pending changesets"; then
          echo "hasChangesets=false" >> $GITHUB_OUTPUT
          echo "No changesets found"
        else
          echo "hasChangesets=true" >> $GITHUB_OUTPUT
          VERSION=$(echo "$STATUS" | grep "Next version:" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')

          if [ -z "$VERSION" ]; then
            echo "::error::Failed to parse next version from champ status output: $STATUS"
            exit 1
          fi

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Found changesets, next version: $VERSION"

          echo "y" | champ version
        fi

    - name: Remove checkout credentials
      if: steps.changesets.outputs.hasChangesets == 'true'
      shell: bash
      run: |
        git config --unset-all http.https://github.com/.extraheader || true

    - name: Create Pull Request
      if: steps.changesets.outputs.hasChangesets == 'true'
      id: pr
      uses: peter-evans/create-pull-request@v8
      with:
        token: ${{ inputs.token }}
        base: ${{ github.event.repository.default_branch }}
        commit-message: 'chore: release ${{ steps.config.outputs.versionPrefix }}${{ steps.changesets.outputs.version }}'
        title: 'chore: release ${{ steps.config.outputs.versionPrefix }}${{ steps.changesets.outputs.version }}'
        body: |
          ## Release ${{ steps.config.outputs.versionPrefix }}${{ steps.changesets.outputs.version }}

          This PR was automatically created by change-champion.

          ### Next Steps
          1. Review the changes
          2. Merge this PR
          3. The release will be tagged automatically

          ---
          🤖 Generated by [change-champion](https://github.com/change-champion/champ)
        branch: ${{ steps.config.outputs.releaseBranchPrefix }}${{ steps.config.outputs.versionPrefix }}${{ steps.changesets.outputs.version }}
        delete-branch: true
        labels: |
          release
          automated
